backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#show'

  namespace :admin do
    resources :users
    resources :channels
    resources :videos do
      scope module: :videos do
        resources :song_items do
          resources :song_diffs
        end
        namespace :song_items do
          resource :bulk, only: %i[new create]
        end
        resources :comments
      end
    end

    resource to: 'homes#show'
  end

  namespace :api, defaults: { format: :json } do
    resource :csrf, only: %i[show]
    resource :user, only: %i[show create]
    resource :session, only: %i[create destroy]

    resources :channels, only: %i[index show]
    resources :videos, only: %i[index show]
    resources :song_items, only: %i[index show]

    namespace :member do
      resources :song_items, only: %i[] do
        resources :song_diffs, only: %i[index create]
      end
    end
  end
end

backend/app/models/video.rb
class Video < ApplicationRecord
  include SongLive

  belongs_to :channel
  has_many :song_items, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :video_id, presence: true, uniqueness: true
  scope :displayed, -> { where(published: true) }

  enum :kind, {
    video: 0,
    live: 10,
    short: 20
  }, prefix: true

  # 方針: コメントを探しに行く→セトリ作成→過去のSongDiffからauthorを埋める→Spotifyを使用
  # ただしSpotifyは精度が低いためspotify_completedの場合も適宜過去のSongDiffからauthorを更新する
  enum :status, {
    ready: 0,
    fetched: 10, # コメントにセトリを探しに行った
    song_items_created: 20, # セトリ(SongItem)を作成した
    fetched_history: 25, # 過去のSongDiffを見てauthorの空白部分で埋められる部分を埋めた
    spotify_fetched: 30, # spotifyのデータからauthorの空白部分で埋められる部分を埋めた
    spotify_completed: 35, # spotifyのデータからauthorの空白部分を埋めた
    completed: 40 # time, title, authorが埋まった
  }, prefix: true

  def self.fetch_and_create!(video_ids)
    response = Youtube.get_videos(video_ids)
    videos = []
    response.items.each do |item|
      # 与えられたチャンネルの動画ではない場合はskip
      next if new.channel.present? && new.channel.channel_id != item.snippet.channel_id

      channel = Channel.find_by(channel_id: item.snippet.channel_id)
      next if channel.blank? # チャンネルがDBに存在しない場合

      video = Video.find_or_initialize_by(video_id: item.id)

      kind = item.live_streaming_details.present? ? 'live' : 'video'
      published_at = item.live_streaming_details&.actual_start_time \
            || item.live_streaming_details&.scheduled_start_time \
            || item.snippet.published_at

      video.update!(
        video_id: item.id,
        title: item.snippet.title,
        response_json: item.to_h,
        kind:,
        channel_id: channel.id,
        published_at:
      )
      videos.push(video)
    end
    videos
  end

  # {
  #   default: {
  #     width: number,
  #     height: number,
  #     url: string,
  #   },
  #   medium: {
  #     width: number,
  #     height: number,
  #     url: string,
  #   },
  #   high: {
  #     width: number,
  #     height: number,
  #     url: string,
  #   },
  # }
  def thumbnails
    response_json.dig('snippet', 'thumbnails')
  end

  def description
    response_json.dig('snippet', 'description')
  end

  def link_url
    Youtube::ENDPOINT + "watch?v=#{video_id}"
  end
end

backend/app/controllers/admin/videos/base.rb
class Admin::Videos::Base < Admin::Base
  before_action :set_video
  before_action :set_channel

  private

  def set_video
    @video = Video.find(params[:video_id])
  end

  def set_channel
    @channel = @video.channel
  end
end

backend/app/controllers/admin/videos/comments_controller.rb
class Admin::Videos::CommentsController < Admin::Videos::Base
  before_action :set_comment, only: %i[show edit update destroy]

  def index
    @comments = @video.comments.all
  end

  def show; end

  def new
    @comment = @video.comments.new
  end

  def edit; end

  def create
    @comment = @video.comments.new(comment_params)

    if @comment.save
      redirect_to admin_video_comments_path(@video), notice: 'Commentが作成されました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to admin_video_comments_path(@video), notice: 'Commentが更新されました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    redirect_to admin_video_comments_path(@video), notice: 'Commentが削除されました。'
  end

  private

  def set_comment
    @comment = @video.comments.find(params[:id])
  end

  def comment_params
    params.expect(comment: %i[status response_json])
  end
end

backend/app/controllers/admin/videos/song_diffs_controller.rb
class Admin::Videos::SongDiffsController < Admin::Videos::Base
  before_action :set_song_item
  before_action :set_song_diff, only: %i[show edit update destroy]

  def index
    @song_diffs = @song_item.song_diffs.all
  end

  def show; end

  def new
    @song_diff = @song_item.song_diffs.new
  end

  def edit; end

  def create
    @song_diff = @song_item.song_diffs.new(song_diff_params)

    if @song_diff.save
      @song_diff.update_status!(params[:song_diff][:status]) if params[:song_diff][:status].present?
      redirect_to admin_video_song_item_song_diffs_path(@video, @song_item), notice: 'Song diffが作成されました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @song_diff.update(song_diff_params)
      @song_diff.update_status!(params[:song_diff][:status]) if params[:song_diff][:status].present?
      redirect_to admin_video_song_item_song_diffs_path(@video, @song_item), notice: 'Song diffが更新されました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @song_diff.destroy
    redirect_to admin_video_song_item_song_diffs_path(@video, @song_item), notice: 'Song diffが削除されました。'
  end

  private

  def set_song_item
    @song_item = @video.song_items.find(params[:song_item_id])
  end

  def set_song_diff
    @song_diff = @song_item.song_diffs.find(params[:id])
  end

  def song_diff_params
    params.expect(song_diff: %i[made_by_id kind time title author])
  end
end

backend/app/controllers/admin/videos/song_items/bulks_controller.rb
class Admin::Videos::SongItems::BulksController < Admin::Videos::Base
  def new; end

  def create
    song_items = if params[:json].present?
                   @video.song_items.create_from_hash!(JSON.parse(params[:json]))
                 elsif params[:comment_id].present?
                   Comment.find(params[:comment_id]).force_create_song_items!
                 elsif params[:comment].present?
                   @video.song_items.create_from_comment_content!(params[:comment])
                 else
                   @video.search_and_create_song_items!
                 end
    if song_items.present? && song_items.filter(&:completed?).count == song_items.count
      @video.update!(status: 'completed')
    elsif song_items.present?
      @video.update!(status: 'song_items_created')
    end
    redirect_to admin_video_song_items_path(@video)
  end
end

backend/app/controllers/admin/videos/song_items_controller.rb
class Admin::Videos::SongItemsController < Admin::Videos::Base
  before_action :set_song_item, only: %i[show edit update destroy]

  def index
    @song_items = @video.song_items.includes(:latest_diff).order('song_diffs.time asc')
  end

  def show; end

  def new
    @song_item = @video.song_items.new
  end

  def edit; end

  def create
    @song_item = @video.song_items.new(song_item_params)
    return render :new, status: :unprocessable_entity unless @song_item.save

    @song_diff = @song_item.song_diffs.new(song_diff_params.merge({ kind: 'auto' }))
    if @song_diff.save
      @song_diff.update_status!('approved')
      redirect_to admin_video_song_items_path(@video), notice: 'Song itemが作成されました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @song_item.update(song_item_params)
      redirect_to admin_video_song_items_path(@video), notice: 'Song itemが更新されました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @song_item.destroy
    redirect_to admin_video_song_items_path(@video), notice: 'Song itemが削除されました。'
  end

  private

  def set_song_item
    @song_item = @video.song_items.find(params[:id])
  end

  def song_item_params
    params.expect(song_item: [:video_id])
  end

  def song_diff_params
    params.require(:song_item).require(:song_diff).permit(:time, :title, :author)
  end
end

backend/app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::Base
  before_action :set_video, only: %i[show edit update destroy]
  before_action :set_channel

  def index
    @only_song_lives = (params[:only_song_lives] || 1).to_i.positive?
    @only_incompleted = (params[:only_incompleted] || 1).to_i.positive?

    scope = @channel.present? ? @channel.videos : Video
    scope = scope.song_lives if @only_song_lives
    scope = scope.where.not(status: 'completed') if @only_incompleted
    scope = scope.order(published_at: :desc).all
    @videos = scope.page(params[:page]).per(20)
  end

  def show; end

  def new
    @video = Video.new
  end

  def edit; end

  def create
    @video = Video.fetch_and_create!([video_params[:video_id]])[0]

    if @video.present?
      redirect_to admin_videos_path(channel_id: @video.channel.id), notice: 'Videoが作成されました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    published = video_params[:published].present? ? video_params[:published] == 'true' : @video.published
    if @video.update({ **video_params, published: })
      redirect_to admin_videos_path(channel_id: @video.channel.id), notice: 'Videoが更新されました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @video.destroy
    redirect_to admin_videos_path(channel_id: @video.channel.id), notice: 'Videoが削除されました。'
  end

  private

  def set_channel
    Rails.logger.debug params[:channel_id]
    @channel = Channel.find_by(id: params[:channel_id] || @video&.channel_id)
  end

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.expect(video: %i[channel_id video_id kind title status published])
  end
end

backend/app/controllers/api/videos_controller.rb
class Api::VideosController < Api::Base
  before_action :set_channel
  before_action :set_video, only: %i[show]

  def index
    scope = @channel.present? ? @channel.videos.displayed : Video.displayed

    # あいまい検索(タイトル・歌手名)
    scope = scope.where('videos.title ILIKE ?', "%#{params[:query]}%") \
              if params[:query].present?
    # 日付で絞り込み
    since_time = params[:since].present? ? Time.zone.parse(params[:since]).beginning_of_day : nil
    until_time = params[:until].present? ? Time.zone.parse(params[:until]).end_of_day : nil
    scope = scope.where(published_at: since_time..until_time)

    # 歌枠のみに絞り込み(歌が1曲以上ある配信に絞る)
    scope = scope.where(id: SongItem.active.select(:video_id)) if params[:only_song_lives].to_i.positive?

    @videos = scope.order(published_at: :desc).page(params[:page]).per(params[:count])
    @total_pages = @videos.total_pages
  end

  def show; end

  private

  def set_channel
    return if params[:channel_id].blank?

    @channel = Channel.kind_published.find_by(id: params[:channel_id])
    if @channel.blank?
      render json: {
        message: 'Channel not found'
      }, status: :bad_request
    end
  end

  def set_video
    @video = Video.find(params[:id])
  end
end

backend/app/views/admin/videos/edit.html.haml
%h1 Video編集

= form_with(model: [:admin, @video]) do |form|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |message|
          %li= message
  .row.mb-3
    .col-md-3.col-form-label.fw-bold channel
    .col-md-9= form.collection_select :channel_id, Channel.all, :id, :name, {}, class: 'form-control'
  .row.mb-3
    .col-md-3.col-form-label.fw-bold title
    .col-md-9= form.text_field :title, class: 'form-control'
  .row.mb-3
    .col-md-3.col-form-label.fw-bold video_id
    .col-md-9= form.text_field :video_id, class: 'form-control'
  .row.mb-3
    .col-md-3.col-form-label.fw-bold kind
    .col-md-9= form.select :kind, Video.kinds_i18n.invert, {}, class: 'form-control'
  .row.mb-3
    .col-md-3.col-form-label.fw-bold Published
    .col-md-9= form.select :published, [['公開', 'true'], ['非公開', 'false']], { value: @video.published ? '1' : '0' }, class: 'form-control'
  .row.mb-3
    .col-md-3.col-form-label.fw-bold Status
    .col-md-9= form.select :status, Video.statuses_i18n.invert, {}, class: 'form-control'
  .row
    .col
      = form.submit '保存', class: 'btn btn-primary d-block w-100'

= link_to '閲覧', admin_video_path(@video)
\|
= link_to '戻る', admin_videos_path

backend/app/views/admin/videos/index.html.haml
- content_for :js, javascript_include_tag('admin/videos'), type: :module

%h1 Video一覧
.px-2.my-3
  %label.form-check
    = check_box_tag :only_song_lives, '1', @only_song_lives, { class: 'form-check-input', id: 'only-song-lives' }
    .check_box_label 歌枠のみ表示
  %label.form-check
    = check_box_tag :only_incompleted, '1', @only_incompleted, { class: 'form-check-input', id: 'only-incompleted' }
    .check_box_label completeでない配信のみ表示

%table.table
  %thead.table-light
    %tr
      %th Thumbnail
      %th Video
      %th Kind
      %th PublishedAt
      %th Published
      %th Status
      %th Title
      %th Action
      %th Links

  %tbody
    %tr
      %td{colspan: 9}= link_to 'video新規作成', new_admin_video_path, class: 'btn btn-primary w-100'
    - @videos.each do |video|
      %tr
        %th= image_tag video.thumbnails["high"]["url"], width: 200
        %td= video.video_id
        %td= video.kind
        %td= video.published_at
        %td= video.published ? '公開' : '非公開'
        %td= video.status
        %td= video.title
        %td
          = form_with(url: admin_video_song_items_bulk_path(video)) do |form|
            = form.submit 'セトリ作成', class: 'btn btn-sm btn-outline-primary'
          = form_with(model: [:admin, video], class: 'mt-1') do |form|
            = form.hidden_field :status, value: 'completed'
            = form.submit 'completedにする', class: 'btn btn-sm btn-outline-primary'
        %td
          = link_to '歌リスト', admin_video_song_items_path(video), class: 'm-1 btn btn-sm btn-outline-primary'
          = link_to 'コメント一覧', admin_video_comments_path(video), class: 'm-1 btn btn-sm btn-outline-primary'
          = link_to 'Youtube', video.link_url, target: :_blank, class: 'm-1 btn btn-sm btn-outline-primary'
          = link_to '閲覧', admin_video_path(video), class: 'm-1 btn btn-sm btn-outline-primary'
          = link_to '編集', edit_admin_video_path(video), class: 'm-1 btn btn-sm btn-outline-primary'
          = link_to '削除', admin_video_path(video), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'm-1 btn btn-sm btn-outline-danger'

.my-2.d-flex.justify-content-center= paginate @videos

backend/app/views/admin/videos/new.html.haml
%h1 Video新規作成

= form_with(model: [:admin, @video]) do |form|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |message|
          %li= message

  .row.mb-3
    .col-md-3.col-form-label.fw-bold video_id
    .col-md-9= form.text_field :video_id, class: 'form-control'

  .row
    .col
      = form.submit '保存', class: 'btn btn-primary d-block w-100'

= link_to '戻る', admin_videos_path

backend/app/views/admin/videos/show.html.haml
%h1 Video
.row.py-1
  .col-md-3.fw-bold リンク
  .col-md-9.row
    .col-6.px-1= link_to '歌一覧', admin_video_song_items_path(@video), class: 'btn btn-outline-primary w-100'
    .col-6.px-1= link_to 'コメント一覧', admin_video_comments_path(@video), class: 'btn btn-outline-primary w-100'
.row.py-1
  .col-md-3.fw-bold Title
  .col-md-9= @video.title
.row.py-1
  .col-md-3.fw-bold Video
  .col-md-9= @video.video_id
.row.py-1
  .col-md-3.fw-bold リンク
  .col-md-9= link_to @video.link_url, @video.link_url, target: :_blank
.row.py-1
  .col-md-3.fw-bold Kind
  .col-md-9= @video.kind
.row.py-1
  .col-md-3.fw-bold PublishedAt
  .col-md-9= @video.published_at
.row.py-1
  .col-md-3.fw-bold Status
  .col-md-9= @video.status
.row.py-1
  .col-md-3.fw-bold Response json
  .col-md-9= @video.response_json.to_json

= link_to '編集', edit_admin_video_path(@video)
\|
= link_to '戻る', admin_videos_path