backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#show'

  namespace :admin do
    resources :users
    resources :channels
    resources :videos do
      scope module: :videos do
        resources :song_items do
          resources :song_diffs
        end
        namespace :song_items do
          resource :bulk, only: %i[new create]
        end
        resources :comments
      end
    end

    resource to: 'homes#show'
  end

  namespace :api, defaults: { format: :json } do
    resource :csrf, only: %i[show]
    resource :user, only: %i[show create]
    resource :session, only: %i[create destroy]

    resources :channels, only: %i[index show]
    resources :videos, only: %i[index show]
    resources :song_items, only: %i[index show]

    namespace :member do
      resources :song_items, only: %i[] do
        resources :song_diffs, only: %i[index create]
      end
    end
  end
end

backend/app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::Base
  def show; end
end

backend/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show; end
end

backend/app/views/admin/homes/show.html.haml
%h3 管理者ページ
.list-group
  = link_to 'ユーザー一覧', admin_users_path, class: 'list-group-item list-group-item-action'
  = link_to 'チャンネル一覧', admin_channels_path, class: 'list-group-item list-group-item-action'
  = link_to '動画一覧', admin_videos_path, class: 'list-group-item list-group-item-action'