backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#show'

  namespace :admin do
    resources :users
    resources :channels
    resources :videos do
      scope module: :videos do
        resources :song_items do
          resources :song_diffs
        end
        namespace :song_items do
          resource :bulk, only: %i[new create]
        end
        resources :comments
      end
    end

    resource to: 'homes#show'
  end

  namespace :api, defaults: { format: :json } do
    resource :csrf, only: %i[show]
    resource :user, only: %i[show create]
    resource :session, only: %i[create destroy]

    resources :channels, only: %i[index show]
    resources :videos, only: %i[index show]
    resources :song_items, only: %i[index show]

    namespace :member do
      resources :song_items, only: %i[] do
        resources :song_diffs, only: %i[index create]
      end
    end
  end
end

backend/app/models/channel.rb
class Channel < ApplicationRecord
  has_many :videos, dependent: :destroy
  validates :channel_id, presence: true, uniqueness: true
  has_many :all_song_items, through: :videos, class_name: 'SongItem', source: :song_items

  enum :kind, {
    hidden: 0,
    published: 100
  }, prefix: true

  enum :status, {
    ready: 0,
    videos_fetched: 50
  }, prefix: true

  def self.fetch_and_create!(channel_ids)
    response = Youtube.get_channels(channel_ids)
    channels = []

    response.items.each do |item|
      channel = Channel.find_or_initialize_by(channel_id: item.id)
      channel.update!(
        channel_id: item.id,
        name: item.snippet.title,
        response_json: item.to_h
      )
      channels.push(channel)
    end
    channels
  end

  # {
  #   default: {
  #     width: number,
  #     height: number,
  #     url: string,
  #   },
  #   medium: {
  #     width: number,
  #     height: number,
  #     url: string,
  #   },
  #   high: {
  #     width: number,
  #     height: number,
  #     url: string,
  #   },
  # }
  def thumbnails
    response_json['snippet']['thumbnails']
  end

  def description
    response_json['snippet']['description']
  end

  def custom_id
    response_json['snippet']['custom_url']
  end

  def search_and_create_recent_videos
    video_ids = Youtube.get_recent_video_ids(channel_id)
    videos.fetch_and_create!(video_ids)
  end

  def search_and_create_all_videos
    video_ids = Youtube.get_all_video_ids(custom_id)
    i = 0
    while i * 50 < video_ids.length
      # 50個ずつ見に行く
      videos.fetch_and_create!(video_ids[(i * 50)...((i + 1) * 50)])
      i += 1
    end
    update!(status: 'videos_fetched')
  end
end

backend/app/controllers/admin/channels_controller.rb
class Admin::ChannelsController < Admin::Base
  before_action :set_channel, only: %i[show edit update destroy]

  def index
    @channels = Channel.all
  end

  def show; end

  def new
    @channel = Channel.new
  end

  def edit; end

  def create
    channel_id = channel_params[:channel_id].presence \
      || Youtube.get_channel_id(channel_params[:channel_link].split('/')[3])
    @channel = Channel.fetch_and_create!([channel_id])[0]

    if @channel.present?
      redirect_to admin_channels_path, notice: 'Channel が作成されました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @channel.update(channel_params)
      redirect_to admin_channels_path, notice: 'Channel が更新されました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @channel.destroy
    redirect_to admin_channels_path, notice: 'Channel が削除されました。'
  end

  private

  def set_channel
    @channel = Channel.find(params[:id])
  end

  def channel_params
    params.expect(channel: %i[channel_id name custom_name kind twitter_id channel_link])
  end
end

backend/app/controllers/api/channels_controller.rb
class Api::ChannelsController < Api::Base
  before_action :set_channel, only: %i[show]
  def index
    @channels = Channel.kind_published.order('random()')
  end

  def show; end

  private

  def set_channel
    @channel = Channel.kind_published.find(params[:id])
  end
end

backend/app/views/admin/channels/edit.html.haml
%h1 チャンネル編集

= form_with(model: [:admin, @channel]) do |form|
  - if @channel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@channel.errors.count, "error")} prohibited this channel from being saved:"
      %ul
        - @channel.errors.full_messages.each do |message|
          %li= message
  
  .row.mb-3
    .col-md-3.col-form-label.fw-bold channel_id
    .col-md-9= form.text_field :channel_id, class: 'form-control'
  .row.mb-3
    .col-md-3.col-form-label.fw-bold name
    .col-md-9= form.text_field :name, class: 'form-control'
  .row.mb-3
    .col-md-3.col-form-label.fw-bold custom name
    .col-md-9= form.text_field :custom_name, class: 'form-control'
  .row.mb-3
    .col-md-3.col-form-label.fw-bold kind
    .col-md-9= form.select :kind, Channel.kinds_i18n.invert, {}, class: 'form-control'
  .row.mb-3
    .col-md-3.col-form-label.fw-bold twitter_id
    .col-md-9= form.text_field :twitter_id, class: 'form-control'
  .row
    .col
      = form.submit '保存', class: 'btn btn-primary d-block w-100'

= link_to '閲覧', admin_channel_path(@channel)
\|
= link_to '戻る', admin_channels_path

backend/app/views/admin/channels/index.html.haml
%h1 チャンネル一覧
%table.table
  %thead.table-light
    %tr
      %th アイコン
      %th Channel id
      %th 名前
      %th Custom name
      %th Kind
      %th Status
      %th Twitter
      %th リンク

  %tbody
    %tr
      %td{colspan: 8}= link_to 'channel新規作成', new_admin_channel_path, class: 'btn btn-primary w-100'
    - @channels.each do |channel|
      %tr
        %td= image_tag channel.thumbnails["default"]["url"], width: 100
        %td= channel.channel_id
        %td= channel.name
        %td= channel.custom_name
        %td= channel.kind
        %td= channel.status
        %td= channel.twitter_id
        %td
          = link_to '動画一覧', admin_videos_path(channel_id: channel.id), class: 'btn btn-sm btn-outline-primary'
          = link_to '閲覧', admin_channel_path(channel), class: 'btn btn-sm btn-outline-primary'
          = link_to '編集', edit_admin_channel_path(channel), class: 'btn btn-sm btn-outline-primary'
          = link_to '削除', admin_channel_path(channel), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-sm btn-outline-danger'

backend/app/views/admin/channels/new.html.haml
%h1 チャンネル新規作成

= form_with(model: [:admin, @channel]) do |form|
  - if @channel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@channel.errors.count, "error")} prohibited this channel from being saved:"
      %ul
        - @channel.errors.full_messages.each do |message|
          %li= message
  
  .row.mb-3
    .col-md-3.col-form-label.fw-bold チャンネルID
    .col-md-9= form.text_field :channel_id, class: 'form-control'
  .row.mb-3
    .col-md-3.col-form-label.fw-bold チャンネルリンク
    .col-md-9= form.text_field :channel_link, class: 'form-control'
  .row
    .col
      = form.submit '保存', class: 'btn btn-primary d-block w-100'

= link_to '戻る', admin_channels_path

backend/app/views/admin/channels/show.html.haml
%h1 チャンネル
.row.py-1
  .col-md-3.fw-bold Channel
  .col-md-9= @channel.channel_id
.row.py-1
  .col-md-3.fw-bold Name
  .col-md-9= @channel.name
.row.py-1
  .col-md-3.fw-bold Custom name
  .col-md-9= @channel.custom_name
.row.py-1
  .col-md-3.fw-bold Kind
  .col-md-9= @channel.kind
.row.py-1
  .col-md-3.fw-bold Status
  .col-md-9= @channel.status
.row.py-1
  .col-md-3.fw-bold Twitter
  .col-md-9= @channel.twitter_id
.row.py-1
  .col-md-3.fw-bold Response json
  .col-md-9= @channel.response_json.to_json

= link_to '編集', edit_admin_channel_path(@channel)
\|
= link_to '戻る', admin_channels_path